# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\周以龙\Desktop\portscanV1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(854, 621)
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.HostName = QtWidgets.QPlainTextEdit(dialog)
        self.HostName.setGeometry(QtCore.QRect(110, 20, 171, 31))
        self.HostName.setOverwriteMode(False)
        self.HostName.setObjectName("HostName")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.HostAdress = QtWidgets.QPlainTextEdit(dialog)
        self.HostAdress.setGeometry(QtCore.QRect(110, 70, 171, 31))
        self.HostAdress.setOverwriteMode(False)
        self.HostAdress.setObjectName("HostAdress")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(330, 20, 102, 24))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.PortMin = QtWidgets.QPlainTextEdit(dialog)
        self.PortMin.setGeometry(QtCore.QRect(440, 20, 61, 31))
        self.PortMin.setOverwriteMode(False)
        self.PortMin.setObjectName("PortMin")
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setGeometry(QtCore.QRect(510, 20, 17, 24))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.PortMax = QtWidgets.QPlainTextEdit(dialog)
        self.PortMax.setGeometry(QtCore.QRect(530, 20, 71, 31))
        self.PortMax.setOverwriteMode(False)
        self.PortMax.setObjectName("PortMax")
        self.label_5 = QtWidgets.QLabel(dialog)
        self.label_5.setGeometry(QtCore.QRect(330, 70, 121, 24))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Internetnumber = QtWidgets.QPlainTextEdit(dialog)
        self.Internetnumber.setGeometry(QtCore.QRect(460, 70, 121, 31))
        self.Internetnumber.setTabChangesFocus(False)
        self.Internetnumber.setOverwriteMode(False)
        self.Internetnumber.setBackgroundVisible(False)
        self.Internetnumber.setObjectName("Internetnumber")
        self.label_6 = QtWidgets.QLabel(dialog)
        self.label_6.setGeometry(QtCore.QRect(590, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.HostnumberMax = QtWidgets.QPlainTextEdit(dialog)
        self.HostnumberMax.setGeometry(QtCore.QRect(780, 70, 51, 31))
        self.HostnumberMax.setOverwriteMode(False)
        self.HostnumberMax.setObjectName("HostnumberMax")
        self.HostnumberMin = QtWidgets.QPlainTextEdit(dialog)
        self.HostnumberMin.setGeometry(QtCore.QRect(710, 70, 41, 31))
        self.HostnumberMin.setOverwriteMode(False)
        self.HostnumberMin.setObjectName("HostnumberMin")
        self.label_7 = QtWidgets.QLabel(dialog)
        self.label_7.setGeometry(QtCore.QRect(760, 70, 17, 24))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 220, 831, 371))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.layoutWidget = QtWidgets.QWidget(dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(280, 590, 295, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StartScanButton = QtWidgets.QPushButton(self.layoutWidget)
        self.StartScanButton.setObjectName("StartScanButton")
        self.horizontalLayout.addWidget(self.StartScanButton)
        self.ClearButton = QtWidgets.QPushButton(self.layoutWidget)
        self.ClearButton.setObjectName("ClearButton")
        self.horizontalLayout.addWidget(self.ClearButton)
        self.ExitButton = QtWidgets.QPushButton(self.layoutWidget)
        self.ExitButton.setObjectName("ExitButton")
        self.horizontalLayout.addWidget(self.ExitButton)
        self.groupBox = QtWidgets.QGroupBox(dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 110, 811, 51))
        self.groupBox.setObjectName("groupBox")
        self.radio_tcpcon = QtWidgets.QRadioButton(self.groupBox)
        self.radio_tcpcon.setGeometry(QtCore.QRect(10, 20, 115, 19))
        self.radio_tcpcon.setChecked(True)
        self.radio_tcpcon.setObjectName("radio_tcpcon")
        self.radio_tcpsyn = QtWidgets.QRadioButton(self.groupBox)
        self.radio_tcpsyn.setGeometry(QtCore.QRect(130, 20, 115, 19))
        self.radio_tcpsyn.setObjectName("radio_tcpsyn")
        self.radio_tcpfin = QtWidgets.QRadioButton(self.groupBox)
        self.radio_tcpfin.setGeometry(QtCore.QRect(220, 20, 115, 19))
        self.radio_tcpfin.setObjectName("radio_tcpfin")
        self.radio_tcpxmas = QtWidgets.QRadioButton(self.groupBox)
        self.radio_tcpxmas.setGeometry(QtCore.QRect(310, 20, 115, 19))
        self.radio_tcpxmas.setObjectName("radio_tcpxmas")
        self.radio_tcpnull = QtWidgets.QRadioButton(self.groupBox)
        self.radio_tcpnull.setGeometry(QtCore.QRect(410, 20, 115, 19))
        self.radio_tcpnull.setObjectName("radio_tcpnull")
        self.radio_udpscan = QtWidgets.QRadioButton(self.groupBox)
        self.radio_udpscan.setGeometry(QtCore.QRect(510, 20, 115, 19))
        self.radio_udpscan.setChecked(False)
        self.radio_udpscan.setObjectName("radio_udpscan")
        self.label_9 = QtWidgets.QLabel(dialog)
        self.label_9.setGeometry(QtCore.QRect(430, 170, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.ScanSate = QtWidgets.QPlainTextEdit(dialog)
        self.ScanSate.setGeometry(QtCore.QRect(510, 180, 321, 31))
        self.ScanSate.setPlainText("")
        self.ScanSate.setOverwriteMode(True)
        self.ScanSate.setObjectName("ScanSate")
        self.label_8 = QtWidgets.QLabel(dialog)
        self.label_8.setGeometry(QtCore.QRect(8, 170, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.checkBox_open = QtWidgets.QCheckBox(dialog)
        self.checkBox_open.setGeometry(QtCore.QRect(86, 178, 131, 31))
        self.checkBox_open.setChecked(False)
        self.checkBox_open.setObjectName("checkBox_open")
        self.checkBox_closed = QtWidgets.QCheckBox(dialog)
        self.checkBox_closed.setGeometry(QtCore.QRect(206, 178, 131, 31))
        self.checkBox_closed.setChecked(False)
        self.checkBox_closed.setObjectName("checkBox_closed")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "PortScanner"))
        self.label.setText(_translate("dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">本地主机名</span></p></body></html>"))
        self.HostName.setPlainText(_translate("dialog", "默认Admin"))
        self.label_2.setText(_translate("dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">本地主机IP</span></p></body></html>"))
        self.HostAdress.setPlainText(_translate("dialog", "默认127.0.0.1"))
        self.label_3.setText(_translate("dialog", "<html><head/><body><p align=\"center\">扫描端口区间</p></body></html>"))
        self.PortMin.setPlainText(_translate("dialog", "0"))
        self.label_4.setText(_translate("dialog", "<html><head/><body><p align=\"center\">到</p></body></html>"))
        self.PortMax.setPlainText(_translate("dialog", "65535"))
        self.label_5.setText(_translate("dialog", "<html><head/><body><p align=\"center\">扫描地址网络号</p></body></html>"))
        self.Internetnumber.setPlainText(_translate("dialog", "0.0.0"))
        self.label_6.setText(_translate("dialog", "<html><head/><body><p align=\"center\">扫描地址主机号</p></body></html>"))
        self.HostnumberMax.setPlainText(_translate("dialog", "255"))
        self.HostnumberMin.setPlainText(_translate("dialog", "0"))
        self.label_7.setText(_translate("dialog", "<html><head/><body><p align=\"center\">到</p></body></html>"))
        self.StartScanButton.setText(_translate("dialog", "开始扫描"))
        self.ClearButton.setText(_translate("dialog", "清空"))
        self.ExitButton.setText(_translate("dialog", "退出程序"))
        self.groupBox.setTitle(_translate("dialog", "扫描方式"))
        self.radio_tcpcon.setText(_translate("dialog", "TCP Connect"))
        self.radio_tcpsyn.setText(_translate("dialog", "TCP SYN"))
        self.radio_tcpfin.setText(_translate("dialog", "TCP FIN"))
        self.radio_tcpxmas.setText(_translate("dialog", "TCP XMAS"))
        self.radio_tcpnull.setText(_translate("dialog", "TCP NULL"))
        self.radio_udpscan.setText(_translate("dialog", "UDP SCAN"))
        self.label_9.setText(_translate("dialog", "<html><head/><body><p align=\"center\">扫描状态：</p></body></html>"))
        self.label_8.setText(_translate("dialog", "<html><head/><body><p align=\"center\">扫描结果</p></body></html>"))
        self.checkBox_open.setText(_translate("dialog", "显示开放端口"))
        self.checkBox_closed.setText(_translate("dialog", "显示关闭端口"))

